language: android
android:
        components:
                - platform-tools
                - build-tools-23.0.1
                - android-23
                - extra-android-m2repository
script:
        - ./gradlew build jacocoTestReport
before_install:
        - chmod +x gradlew
        - pip install codecov
branches:
        only:
                - master
after_success:
        - codecov
